### ISSUE TITLE
Merge components into monolithic repository

### ISSUE THREAD

**Issue by vwchu** [yusend/coreflightexec#4]
#### Resources:
  - https://gregoryszorc.com/blog/2014/09/09/on-monolithic-repositories/
  - strongloop/loopback-next#1
  - https://medium.com/@bebraw/the-case-for-monorepos-907c1361708a#.90y1b43up
  - http://danluu.com/monorepo/
  - https://lernajs.io/

**Comment by kmenezes** [comment]
What is this for ?

**Comment by Ekram-B** [comment]
who added you back to the GitHub as an owner?

**Comment by vwchu** [comment]
@Ekram-B Hugh Chesser (@hchesser)

@kmenezes 
- Merge the `cfs-*` + `osal` repos into this repo, for easier maintenance and cleanup.
- Plus, I need to update the `cfs-*` modules, some are outdated
